apiVersion: v1
name: mec
version: 1.0.0
description: MEC middlebox kernel module.
type: application
keywords:
  - edge computing
  - mec
  - OAI
  - middlebox
home: http://nems.cs.nctu.edu.tw/release/
sources:
  - https://hub.docker.com/r/nemsnctu/mec
maintainers:
  - name: nemslab-nctu
    email: nems@g2.nctu.edu.tw
appVersion: 1.0.0
deprecated: false
